#!/bin/bash
output=$(g++ main.cpp Utility.cpp -o sudoku.exe 2>&1) 
if [[ $? != 0 ]]; then
    # There was an error, display the error in $output
    echo -e "Error:\n$output" 
else
    # Compilation successfull
    exec ./sudoku.exe
fi
